import os
from pathlib import Path
from typing import Dict, Any, Optional
from .config import config_mgr

class ZrxScaffolder:
    def __init__(self):
        pass

    def scaffold_cpp_project(
        self,
        target_dir: str,
        project_name: str = "MyZrxPlugin",
        version: str = "2026",
        command_name: str = "MYCMD"
    ) -> Dict[str, Any]:
        p = Path(target_dir)
        p.mkdir(parents=True, exist_ok=True)

        sdk_path = config_mgr.get_sdk_path(version)
        sdk_str = str(sdk_path) if sdk_path else r"D:\zwcad\ZRXSDK"

        # 1. entrypoint.cpp
        cpp_content = f'''// Generated by ZRX-MCP for ZWCAD {version}
#include <tchar.h>
#include <afxwin.h>
#include <aced.h>
#include <rxregsvc.h>
#include <adslib.h>
#include <dbapserv.h>
#include <dbmain.h>

void do_{command_name.lower()}()
{{
    acutPrintf(_T("\\nHello from {project_name}! Command '{command_name}' executed.\\n"));
}}

void initApp()
{{
    // Register commands
    acedRegCmds->addCommand(
        _T("{project_name.upper()}_GROUP"),
        _T("{command_name.upper()}"),
        _T("{command_name.upper()}"),
        ACRX_CMD_MODAL,
        do_{command_name.lower()}
    );
    acutPrintf(_T("\\n[{project_name}] loaded successfully. Type '{command_name}' to run.\\n"));
}}

void unloadApp()
{{
    acedRegCmds->removeGroup(_T("{project_name.upper()}_GROUP"));
    acutPrintf(_T("\\n[{project_name}] unloaded.\\n"));
}}

extern "C" AcRx::AppRetCode 
zcrxEntryPoint(AcRx::AppMsgCode msg, void* pkt)
{{
    switch (msg)
    {{
    case AcRx::kInitAppMsg:
        acrxDynamicLinker->unlockApplication(pkt);
        acrxRegisterAppMDIAware(pkt);
        initApp();
        break;
    case AcRx::kUnloadAppMsg:
        unloadApp();
        break;
    default:
        break;
    }}
    return AcRx::kRetOK;
}}
'''

        # 2. .def file
        def_content = f'''LIBRARY "{project_name}.zrx"
EXPORTS
    zcrxEntryPoint   PRIVATE
    zcrxGetApiVersion PRIVATE
'''

        # 3. Headless build.py with hot-unlocking
        build_py_content = f'''import subprocess
import os
import sys
import time
from pathlib import Path

# Paths
SDK_DIR = r"{sdk_str}"
OUTPUT_NAME = "{project_name}.zrx"
PROJECT_DIR = Path(__file__).resolve().parent

os.chdir(PROJECT_DIR)

# Hot-unlocking if locked by CAD
target_file = Path(OUTPUT_NAME)
if target_file.exists():
    try:
        target_file.unlink()
    except Exception:
        old_file = PROJECT_DIR / f"{project_name}_{{int(time.time())}}.zrx.old"
        try:
            target_file.rename(old_file)
            print(f"[NOTE] {{OUTPUT_NAME}} locked by running CAD, renamed to {{old_file.name}}")
        except Exception as e:
            print(f"[WARN] Failed to rename locked file: {{e}}")

# Compiler setup
VCVARS = r"{config_mgr.find_vcvarsall() or ''}"
if not VCVARS or not os.path.exists(VCVARS):
    print("[ERROR] vcvarsall.bat not found. Please edit build.py with your MSVC path.")
    sys.exit(1)

inc_dirs = [
    os.path.join(SDK_DIR, "inc"),
    os.path.join(SDK_DIR, "arxport", "inc-x64"),
    os.path.join(SDK_DIR, "arxport", "inc")
]
lib_dirs = [
    os.path.join(SDK_DIR, "lib-x64")
]

inc_flags = " ".join([f'/I"{{d}}"' for d in inc_dirs if os.path.exists(d)])
lib_flags = " ".join([f'/LIBPATH:"{{d}}"' for d in lib_dirs if os.path.exists(d)])

sources = ["entrypoint.cpp"]
libs = [
    "ZWCAD.lib", "ZwAuto.lib", "ZwZrx.lib", "ZwDatabase.lib", 
    "ZwRx.lib", "ZwGeometry.lib", "ZwdUI.lib", "ZwUI.lib", 
    "ZwBase.lib", "ZwGs.lib", "ZwPAL.lib", "ZwTc.lib",
    "user32.lib", "kernel32.lib", "gdi32.lib", "shell32.lib"
]

print("=== Building {project_name}.zrx ===")
compile_cmd = (
    f'call "{{VCVARS}}" x64 && '
    f'cl /nologo /utf-8 /O2 /MD /EHsc /D_AFXDLL /DUNICODE /D_UNICODE /DWIN32 /D_WINDOWS /D_USRDLL /D_WIN32_WINNT=0x0600 '
    f'{{inc_flags}} /c {{" ".join(sources)}} && '
    f'link /nologo /DLL /DEF:{project_name}.def /OUT:"{{OUTPUT_NAME}}" {{lib_flags}} *.obj {{" ".join(libs)}}'
)

ret = subprocess.run(compile_cmd, shell=True)
if ret.returncode != 0:
    print("\\n[ERROR] Build FAILED!")
    sys.exit(1)

print(f"\\n=== [SUCCESS] {{OUTPUT_NAME}} generated successfully! ===")
'''

        # 4. build.bat
        build_bat_content = f'''@echo off
chcp 65001 >nul
echo Building {project_name} ...
python "%~dp0build.py"
if errorlevel 1 (
    echo [Build Failed]
    pause
    exit /b 1
)
echo [Build Success]
'''

        # Write files
        files_created = []
        (p / "entrypoint.cpp").write_text(cpp_content, encoding="utf-8")
        files_created.append("entrypoint.cpp")
        (p / f"{project_name}.def").write_text(def_content, encoding="utf-8")
        files_created.append(f"{project_name}.def")
        (p / "build.py").write_text(build_py_content, encoding="utf-8")
        files_created.append("build.py")
        (p / "build.bat").write_text(build_bat_content, encoding="utf-8")
        files_created.append("build.bat")

        return {
            "success": True,
            "project_name": project_name,
            "target_dir": str(p),
            "files": files_created,
            "version": version,
            "message": f"C++ ZRX project '{project_name}' scaffolded with headless build.py support."
        }

    def scaffold_dotnet_project(
        self,
        target_dir: str,
        project_name: str = "MyZrxDotNet",
        version: str = "2026",
        command_name: str = "MYNETCMD"
    ) -> Dict[str, Any]:
        p = Path(target_dir)
        p.mkdir(parents=True, exist_ok=True)

        sdk_path = config_mgr.get_sdk_path(version)
        inc_dir = str(sdk_path / "inc") if sdk_path else r"D:\zwcad\ZRXSDK\inc"

        csproj_content = f'''<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net47</TargetFramework>
    <Platforms>x64</Platforms>
    <PlatformTarget>x64</PlatformTarget>
    <RootNamespace>{project_name}</RootNamespace>
    <AssemblyName>{project_name}</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="ZwManaged">
      <HintPath>{inc_dir}\\ZwManaged.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="ZwDatabaseMgd">
      <HintPath>{inc_dir}\\ZwDatabaseMgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>
</Project>
'''

        cs_content = f'''using System;
using ZwSoft.ZwCAD.Runtime;
using ZwSoft.ZwCAD.ApplicationServices;
using ZwSoft.ZwCAD.DatabaseServices;
using ZwSoft.ZwCAD.EditorInput;

[assembly: ExtensionApplication(typeof({project_name}.PluginApp))]
[assembly: CommandClass(typeof({project_name}.Commands))]

namespace {project_name}
{{
    public class PluginApp : IExtensionApplication
    {{
        public void Initialize()
        {{
            Editor ed = Application.DocumentManager.MdiActiveDocument.Editor;
            ed.WriteMessage("\\n[{project_name}] .NET Plugin Loaded. Type '{command_name}' to run.\\n");
        }}

        public void Terminate()
        {{
        }}
    }}

    public class Commands
    {{
        [CommandMethod("{command_name}")]
        public void RunCommand()
        {{
            Document doc = Application.DocumentManager.MdiActiveDocument;
            Database db = doc.Database;
            Editor ed = doc.Editor;

            using (Transaction tr = db.TransactionManager.StartTransaction())
            {{
                ed.WriteMessage("\\nHello from {project_name} .NET Plugin!\\n");
                tr.Commit();
            }}
        }}
    }}
}}
'''

        (p / f"{project_name}.csproj").write_text(csproj_content, encoding="utf-8")
        (p / "Commands.cs").write_text(cs_content, encoding="utf-8")

        return {
            "success": True,
            "project_name": project_name,
            "target_dir": str(p),
            "files": [f"{project_name}.csproj", "Commands.cs"],
            "version": version,
            "message": f".NET ZRX project '{project_name}' scaffolded for ZWCAD {version}."
        }

    def generate_boilerplate(self, pattern_type: str, name: str = "MyEntity") -> str:
        pt = pattern_type.lower().strip()
        if "custom_entity" in pt or "entity" in pt:
            return f'''// Boilerplate: Custom Entity ({name}) inheriting from ZcDbEntity
#include <dbmain.h>
#include <dbents.h>
#include <geassign.h>

class {name} : public ZcDbEntity
{{
public:
    ZCRX_DECLARE_MEMBERS({name});

    {name}() : m_center(0, 0, 0), m_radius(10.0) {{}}
    virtual ~{name}() {{}}

    // Geometry data
    ZcGePoint3d center() const {{ assertReadEnabled(); return m_center; }}
    void setCenter(const ZcGePoint3d& pt) {{ assertWriteEnabled(); m_center = pt; }}

    double radius() const {{ assertReadEnabled(); return m_radius; }}
    void setRadius(double r) {{ assertWriteEnabled(); m_radius = r; }}

    // Required overrides
    virtual Zcad::ErrorStatus dwgInFields(ZcDbDwgFiler* pFiler) override
    {{
        assertWriteEnabled();
        Zcad::ErrorStatus es = ZcDbEntity::dwgInFields(pFiler);
        if (es != Zcad::kOk) return es;
        pFiler->readPoint3d(&m_center);
        pFiler->readDouble(&m_radius);
        return pFiler->filerStatus();
    }}

    virtual Zcad::ErrorStatus dwgOutFields(ZcDbDwgFiler* pFiler) const override
    {{
        assertReadEnabled();
        Zcad::ErrorStatus es = ZcDbEntity::dwgOutFields(pFiler);
        if (es != Zcad::kOk) return es;
        pFiler->writePoint3d(m_center);
        pFiler->writeDouble(m_radius);
        return pFiler->filerStatus();
    }}

    virtual ZSoft::Boolean subWorldDraw(ZcGiWorldDraw* mode) override
    {{
        assertReadEnabled();
        mode->geometry().circle(m_center, m_radius, ZcGeVector3d::kZAxis);
        return ZSoft::kTrue;
    }}

    virtual Zcad::ErrorStatus subGetGripPoints(ZcGePoint3dArray& gripPoints, ZcDbIntArray& osnapModes, ZcDbIntArray& geomIds) const override
    {{
        assertReadEnabled();
        gripPoints.append(m_center);
        gripPoints.append(m_center + ZcGeVector3d::kXAxis * m_radius);
        return Zcad::kOk;
    }}

    virtual Zcad::ErrorStatus subMoveGripPointsAt(const ZcDbIntArray& indices, const ZcGeVector3d& offset) override
    {{
        assertWriteEnabled();
        for (int i = 0; i < indices.length(); ++i)
        {{
            int idx = indices[i];
            if (idx == 0) m_center += offset;
            else if (idx == 1) m_radius += offset.length();
        }}
        return Zcad::kOk;
    }}

private:
    ZcGePoint3d m_center;
    double m_radius;
}};

ZCRX_DXF_DEFINE_MEMBERS({name}, ZcDbEntity,
    ZcDb::kDHL_CURRENT, ZcDb::kMReleaseCurrent,
    ZcDbProxyEntity::kNoErase,
    {name.upper()},
    "{name.upper()}APP");
'''
        elif "jig" in pt:
            return f'''// Boilerplate: Interactive Jig ({name}) inheriting from ZcEdJig
#include <dbjig.h>
#include <dbents.h>

class {name} : public ZcEdJig
{{
public:
    {name}(ZcDbCircle* pCircle) : m_pCircle(pCircle), m_curRadius(1.0) {{}}

    Zcad::ErrorStatus doJig()
    {{
        setUserInputControls((UserInputControls)(kAccept3dCoordinates | kNoNegativeResponseAccepted));
        setDispPrompt(_T("\\nSpecify radius: "));
        return drag();
    }}

    virtual DragStatus sampler() override
    {{
        DragStatus stat = acquireDist(m_curRadius, m_pCircle->center());
        if (stat == kNormal)
        {{
            if (fabs(m_curRadius - m_pCircle->radius()) < 1e-4)
                return kNoChange;
        }}
        return stat;
    }}

    virtual ZSoft::Boolean update() override
    {{
        m_pCircle->setRadius(m_curRadius);
        return ZSoft::kTrue;
    }}

    virtual ZcDbEntity* entity() const override
    {{
        return m_pCircle;
    }}

private:
    ZcDbCircle* m_pCircle;
    double m_curRadius;
}};
'''
        elif "transaction" in pt:
            return f'''// Boilerplate: Safe Transaction & Appending Entity to Model Space
#include <dbapserv.h>
#include <dbmain.h>
#include <dbsymtb.h>
#include <actrans.h>

Acad::ErrorStatus appendToModelSpace(ZcDbEntity* pEnt, ZcDbObjectId& outId)
{{
    ZcDbDatabase* pDb = acdbHostApplicationServices()->workingDatabase();
    if (!pDb || !actrTransactionManager) return Acad::eNullObjectPointer;

    ZcTransaction* pTr = actrTransactionManager->startTransaction();
    if (!pTr) return Acad::eNullObjectPointer;

    ZcDbBlockTable* pBT = nullptr;
    Acad::ErrorStatus es = pTr->getObject((ZcDbObject*&)pBT, pDb->blockTableId(), ZcDb::kForRead);
    if (es != Acad::eOk) {{ actrTransactionManager->abortTransaction(); return es; }}

    ZcDbObjectId msId;
    es = pBT->getAt(ACDB_MODEL_SPACE, msId);
    if (es != Acad::eOk) {{ actrTransactionManager->abortTransaction(); return es; }}

    ZcDbBlockTableRecord* pBTR = nullptr;
    es = pTr->getObject((ZcDbObject*&)pBTR, msId, ZcDb::kForWrite);
    if (es != Acad::eOk) {{ actrTransactionManager->abortTransaction(); return es; }}

    es = pBTR->appendZcDbEntity(outId, pEnt);
    if (es == Acad::eOk)
    {{
        actrTransactionManager->addNewlyCreatedDBRObject(pEnt);
        actrTransactionManager->endTransaction();
    }}
    else
    {{
        delete pEnt;
        actrTransactionManager->abortTransaction();
    }}
    return es;
}}
'''
        return f"// Unknown pattern type '{pattern_type}'. Supported: 'custom_entity', 'jig', 'transaction'."

scaffolder = ZrxScaffolder()
